version: '3.1'
services:
  travel-zipkin:
    restart: always
    image: 192.168.219.128:5000/travel-zipkin
    container_name: travel-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network

networks:
  zipkin_network: