spring:
  application:
    name: travel-admin
  zipkin:
    base-url: http://192.168.219.129:9411

server:
  port: 8084

mybatis:
  type-aliases-package: com.travel.api.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.219.129:8761/eureka/,http://192.168.219.129:8861/eureka/,http://192.168.219.129:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info



