version: '3.1'
services:
  travel-zuul:
    restart: always
    image: 192.168.219.128:5000/travel-zuul
    container_name: travel-zuul
    ports:
      - 80:80
    networks:
      - zuul_network


networks:
  zuul_network: