spring:
  application:
    name: travel-zuul

server:
  port: 8769

#zuul:
#  routes:
#    backend-admin:
#      path: /backend/admin/**
#      serviceId: travel-web-admin
#    backend-posts:
#      path: /backend/posts/**
#      serviceId: travel-web-posts